<a href="https://colab.research.google.com/github/sclaudiobr/algoritmos-py/blob/master/conv_meridiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Fórmula de cálculo da convergência meridiana a partir das coordenadas geodésicas no Sistema Topográfico Local

<p>$\gamma _p = -\left [ \triangle \lambda''sen \varphi_m sec \frac{\triangle \varphi}{2}+ F (\triangle \lambda'')^3 \right ]$
<p>$\triangle \lambda '' = (\lambda_p-\lambda_0)\times 3600$
<p>$\triangle \varphi = \varphi_p-\varphi_0$
<p>$F = \frac{sen \varphi_m cos \varphi_m sen^21''}{12}$

γp é a convergência meridiana no ponto considerado;
<p>ϕo é a latitude da origem do sistema;
<p>ϕp é a latitude do ponto geodésico de apoio imediato 
considerado;
<p>λo é a longitude da origem do sistema;
<p>ϕm é a latitude média entre o ponto geodésico de
apoio imediato considerado (P) e a origem do sistema (O).

$\begin{bmatrix}
T\\ 
U\\ 
V
\end{bmatrix} \times \begin{bmatrix}
1 & 0 & 0\\ 
0 & sen \varphi_0 & cos \varphi_0\\ 
0 & -cos \varphi_0 & sen\varphi_0
\end{bmatrix} \times \begin{bmatrix}
-sen \lambda_0 & cos\lambda_0  & 0 \\ 
-cos \lambda_0 & -sen \lambda_0  & 0 \\ 
 0 & 0 & 1 
\end{bmatrix} \times \begin{bmatrix}
X-Y_0\\ 
Y-Y_0\\ 
Z-Z_0
\end{bmatrix}$
<p>
$\begin{bmatrix}
-sen \lambda & cos\lambda  & 0 \\ 
-sen\varphi \times cos \lambda & -sen\varphi \times sen \lambda & cos \varphi \\ 
cos \varphi \times cos \lambda & cos\varphi \times sen \lambda  & sen \varphi 
\end{bmatrix} \times \begin{bmatrix}
\triangle_X  & \\ 
\triangle_Y  & \\
\triangle_Z 
\end{bmatrix} = \begin{bmatrix}
t\\ 
u\\ 
v
\end{bmatrix} $

In [0]:
import numpy as np
import math as mt

# Coordenadas da base

# ------ TROQUE OS VALORES AQUI
lat = float(-29.72016974) # <---- coordenada lat da base
long = float(-53.8624448) # <---- coordenada long da base
a11 = float((-1)*mt.sin(mt.radians(long)))
a12 = float(mt.cos(mt.radians(long)))
a13 = float(0)
a21 = float((-1*(mt.sin(mt.radians(lat))))*mt.cos(mt.radians(long)))
a22 = float(((-1)*mt.sin(mt.radians(lat)))*mt.sin(mt.radians(long)))
a23 = float(mt.cos(mt.radians(lat)))
a31 = float(mt.cos(mt.radians(lat))*mt.cos(mt.radians(long)))
a32 = float(mt.cos(mt.radians(lat))*mt.sin(mt.radians(long)))
a33 = float(mt.sin(mt.radians(lat)))

# Tabela de Distâncias entre a estação e os pontos E(x,y)

# ========TROQUE OS VALORES AQUI
b12 = float(3269328.63996) # <----- coordenada X da base (0)
b11 = float(3269228.037534) # <---  coordenada X do ponto
b22 = float(-4477201.32452) # <---  coordenada Y da base
b21 = float(-4477297.196369) # <--  coordenada Y do ponto
b32 = float(-3143535.63152) # <---  coordenada Z da base
b31 = float(-3143500.393682) # <--  coordenda Z do ponto


In [3]:
A=np.array([
    [a11,a12,a13],
    [a21,a22,a23],
    [a31,a32,a33],
])

B=np.array([
    [b11,b12],
    [b21,b22],
    [b31,b32],
])
print("Matriz A: ")
print(A)
print(f'{len(A)} X {len(A[0])}')
print("-="*20)

Matriz A: 
[[ 0.80760351  0.58972584  0.        ]
 [ 0.29236509 -0.40038109  0.86845705]
 [ 0.51215156 -0.70136896 -0.49576442]]
3 X 3
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


$\begin{bmatrix}
-sen \lambda & cos\lambda  & 0 \\ 
-sen\varphi \times cos \lambda & -sen\varphi \times sen \lambda & cos \varphi \\ 
cos \varphi \times cos \lambda & cos\varphi \times sen \lambda  & sen \varphi 
\end{bmatrix}$

In [4]:
print("Matriz de distâncias")
print(B)
print(f'{len(B)}X{len(B[0])}')

Matriz de distâncias
[[ 3269228.037534  3269328.63996 ]
 [-4477297.196369 -4477201.32452 ]
 [-3143500.393682 -3143535.63152 ]]
3X2


$ \begin{bmatrix}
X_1 - X_0  & \\ 
Y_1 - Y_0  & \\
Z_1 - Z_0 
\end{bmatrix}$

In [5]:
C=np.array([
    [0.00000],
    [0.00000],
    [0.00000],
])
for i in range(len(B)):
    for j in range(len(B[0])):
        C[i][0] = B[i][1]-B[i][0]
print(C)

[[100.602426]
 [ 95.871849]
 [-35.237838]]


In [6]:
D=np.array([
    [0.00000],
    [0.00000],
    [0.00000],
])
for i in range (len(A)):
    for j in range(len(C[0])):
        for k in range(len(C)):
            D[i][j] += A[i][k]*C[k][j]
print(D)

[[137.78497924]
 [-39.57518679]
 [  1.75181636]]


$ \begin{bmatrix}
 \triangle_X  & \\ 
 \triangle_Y  & \\
 \triangle_Z 
\end{bmatrix}$