<a href="https://colab.research.google.com/github/sclaudiobr/algoritmos-py/blob/master/MMQ_Simplificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [94]:
# Matrizes de entrada
t = np.array([[-20,1],[10,1],[70,1]])
c = np.array([[0.128],[0.133],[0.144]])
print(t)
print('--'*5)
print(c)

[[-20   1]
 [ 10   1]
 [ 70   1]]
----------
[[0.128]
 [0.133]
 [0.144]]


In [97]:
# 1º passo - Determinar o valor de Theta multiplicando a transposta de t por t
theta = t.transpose().dot(t)
theta

array([[5400,   60],
       [  60,    3]])

In [99]:
# 2º passo - Calcular a inversa de Theta
itheta = np.linalg.inv(theta)
itheta

array([[ 2.38095238e-04, -4.76190476e-03],
       [-4.76190476e-03,  4.28571429e-01]])

In [100]:
# 3º passo -  Multiplicar a inversa de theta (itheta) pela trasnposta de theta (itheta x theta transposta)
eitheta = itheta.dot(t.transpose())
eitheta

array([[-0.00952381, -0.00238095,  0.01190476],
       [ 0.52380952,  0.38095238,  0.0952381 ]])

In [81]:
# 4º localizando os coeficitentes A e B
coeficientes = eitheta.dot(c)
coeficientes

array([[0.00017857],
       [0.13142857]])

In [91]:
print('Coeficiente angular (A)',coeficientes[0,0])
print('Constante da Reta (B)',coeficientes[1,0])

Coeficiente angular (A) 0.00017857142857142833
Constante da Reta (B) 0.13142857142857142


In [0]:
# Tudo Junto ( os 4 passos em uma só função)
def fMmq(t,c):
  coef = (np.linalg.inv((t.transpose().dot(t)))).dot(t.transpose()).dot(c)
  return coef

In [106]:
# Saída
print(fMmq(t,c))

[[0.00017857]
 [0.13142857]]


In [0]:
# outros dados - teste da função
x = np.array([[1,1],[2,1],[3,1],[4,1],[5,1],[6,1]])
y = np.array([[80.5],[81.6],[82.1],[83.7],[83.9],[85]])

In [110]:
print(fMmq(x,y))

[[ 0.88571429]
 [79.7       ]]
