<a href="https://colab.research.google.com/github/sclaudiobr/algoritmos-py/blob/master/MMQ_Simplificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
t = np.array([[-20,1],[10,1],[70,1]])
c = np.array([[0.128],[0.133],[0.144]])

In [0]:
# 1º passo - Determinar o valor de Teta
def fTheta(t,c):
  theta = t.transpose().dot(t)
  return theta
theta = fTheta(t,t) 

In [0]:
# 2º passo - Calcular a inversa de Theta
itheta = np.linalg.inv(theta)

In [0]:
# 3º passo -  Multiplicar a inversa de theta (itheta) pela trasnposta de theta (itheta x theta transposta)
eitheta = itheta.dot(t.transpose())

In [47]:
# 4º localizando os coeficitentes
eitheta.dot(c)

array([[0.00017857],
       [0.13142857]])

In [60]:
# Tudo Junto
def fMmq(t,c):
  theta = (np.linalg.inv((t.transpose().dot(t)))).dot(t.transpose()).dot(c)
  return theta
print(fMmq(t,c))

[[0.00017857]
 [0.13142857]]


In [0]:
# outros dados - teste da função
x = np.array([[1,1],[2,1],[3,1],[4,1],[5,1],[6,1]])
y = np.array([[80.5],[81.6],[82.1],[83.7],[83.9],[85]])

In [79]:
print(fMmq(x,y))

[[ 0.88571429]
 [79.7       ]]
